USE codeup_test_db;
DROP TABLE IF EXISTS albums;
CREATE TABLE albums (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    artist VARCHAR(50) NOT NULL,
    name VARCHAR(50) DEFAULT 'NONE',
    release_date SMALLINT UNSIGNED NOT NULL,
    sales DOUBLE PRECISION (11,2),
    genre VARCHAR(1000) NOT NULL,
    PRIMARY KEY (id)
);
